### ISSUE TITLE
npm install on Macos not work

### ISSUE THREAD

**Issue by ObscurusGrassator** [mathquis/node-personal-wakeword#11]
Node v18.8.0:
```
npm i
npm ERR! code 1
npm ERR! path /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/gist/src/binding.o
npm ERR! Failed to execute '/Users/xxx/.nvm/versions/node/v18.8.0/bin/node /Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64/gist.node --module_name=gist --module_path=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.8.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64/gist.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/mathquis/node-gist/releases/download/1.0.3/gist-v1.0.3-node-v108-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mathquis/node-gist/releases/download/1.0.3/gist-v1.0.3-node-v108-darwin-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @mathquis/node-gist@1.0.3 and node@18.8.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/mathquis/node-gist/releases/download/1.0.3/gist-v1.0.3-node-v108-darwin-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.8.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.8.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/18.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/18.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/18.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.8.0 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! clang: error: no such file or directory: '2/node_modules/@mathquis/node-gist/node_modules/node-addon-api'
npm ERR! make: *** [Release/obj.target/gist/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/xxx/.nvm/versions/node/v18.8.0/bin/node" "/Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64/gist.node" "--module_name=gist" "--module_path=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
npm ERR! gyp ERR! node -v v18.8.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/xxx/.nvm/versions/node/v18.8.0/bin/node /Users/xxx/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64/gist.node --module_name=gist --module_path=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v108-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/xxx/.nvm/versions/node/v18.8.0/bin/node" "/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
npm ERR! node-pre-gyp ERR! node -v v18.8.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2022-10-29T17_41_54_178Z-debug-0.log
```

Node v16.18.0:
```
npm i
npm ERR! code 1
npm ERR! path /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/gist/src/binding.o
npm ERR! Failed to execute '/Users/xxx/.nvm/versions/node/v16.18.0/bin/node /Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64/gist.node --module_name=gist --module_path=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.18.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64/gist.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/mathquis/node-gist/releases/download/1.0.3/gist-v1.0.3-node-v93-darwin-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mathquis/node-gist/releases/download/1.0.3/gist-v1.0.3-node-v93-darwin-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @mathquis/node-gist@1.0.3 and node@16.18.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/mathquis/node-gist/releases/download/1.0.3/gist-v1.0.3-node-v93-darwin-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.18.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.18.0/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/16.18.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/16.18.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/16.18.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.0 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! clang: error: no such file or directory: '2/node_modules/@mathquis/node-gist/node_modules/node-addon-api'
npm ERR! make: *** [Release/obj.target/gist/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/xxx/.nvm/versions/node/v16.18.0/bin/node" "/Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64/gist.node" "--module_name=gist" "--module_path=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
npm ERR! gyp ERR! node -v v16.18.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/xxx/.nvm/versions/node/v16.18.0/bin/node /Users/xxx/.nvm/versions/node/v16.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64/gist.node --module_name=gist --module_path=/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/lib/binding/Release/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/xxx/.nvm/versions/node/v16.18.0/bin/node" "/Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
npm ERR! node-pre-gyp ERR! node -v v16.18.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2022-10-29T17_42_43_230Z-debug-0.log
```

Node v14.20.1:
```
npm i

> @mathquis/node-gist@1.0.3 preinstall /Users/xxx/Desktop/test 2/node_modules/@mathquis/node-gist
> npm install @mapbox/node-pre-gyp

npm notice created a lockfile as package-lock.json. You should commit this file.
+ @mapbox/node-pre-gyp@1.0.10
added 56 packages from 22 contributors and audited 56 packages in 1.419s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> node-vad@1.1.4 install /Users/xxx/Desktop/test 2/node_modules/node-vad
> node-gyp rebuild

  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/complex_fft.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/ilbc_specific_functions.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/levinson_durbin.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/min_max_operations.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/randomization_functions.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/real_fft.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/resample.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/resample_48khz.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/resample_by_2.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/resample_by_2_internal.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/resample_fractional.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/spl_core.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/spl_init.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/splitting_filter.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/spl_sqrt.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/spl/spl_sqrt_floor.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/vad/vad_core.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/vad/vad_filterbank.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/vad/vad_gmm.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/vad/vad_sp.o
  CC(target) Release/obj.target/webrtc_vad/vendor/webrtc_vad/vad/webrtc_vad.o
  LIBTOOL-STATIC Release/webrtc_vad.a
env: python: No such file or directory
make: *** [Release/webrtc_vad.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v14.20.1/bin/node" "/Users/xxx/.nvm/versions/node/v14.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/Desktop/test 2/node_modules/node-vad
gyp ERR! node -v v14.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN test 2 No description
npm WARN test 2 No repository field.
npm WARN test 2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-vad@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-vad@1.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2022-10-29T17_46_20_812Z-debug.log
```

**Comment by mathquis** [comment]
This package has dependencies that do not support MacOS.

Until these dependencies support MacOS nothing can be done on this end.

**Comment by ObscurusGrassator** [comment]
This information should be given in README.
